MAIN_KEY = "SERVER_MAIN_PASSWORD"
PUBLIC_KEY = "SERVER_KEY_PUBLIC"
PRIVATE_KEY = "SERVER_KEY_PRIVATE"

TYPE_NODE: str = "NODE"
TYPE_CLIENT: str = "CLIENT"
TYPE_USER: str = "USER"

COMPONENT_TYPES: list[str] = [
    TYPE_NODE,
    TYPE_CLIENT,
    TYPE_USER,
]
