TYPE_SERVER: str = "SERVER"
TYPE_CLIENT: str = "CLIENT"
TYPE_WORKER: str = "WORKER"
TYPE_WORKBENCH: str = "WORKBENCH"

COMPONENT_TYPES: list[str] = [
    TYPE_SERVER,
    TYPE_CLIENT,
    TYPE_WORKER,
    TYPE_WORKBENCH,        
]
