TYPE_SERVER: str = "SERVER"
TYPE_CLIENT: str = "CLIENT"
TYPE_WORKER: str = "WORKER"
TYPE_USER: str = "USER"

COMPONENT_TYPES: list[str] = [
    TYPE_SERVER,
    TYPE_CLIENT,
    TYPE_WORKER,
    TYPE_USER,
]
